quarkus.http.port=8081

quarkus.native.debug.enabled=true
quarkus.native.additional-build-args=-O0,-H:-OmitInlinedMethodDebugLineInfo,-H:+SourceLevelDebug,-H:+TrackNodeSourcePosition,-H:+DebugCodeInfoUseSourceMappings,-H:-DeleteLocalSymbols
quarkus.rest-client.read-timeout=7200000
quarkus.vertx.max-event-loop-execute-time=2H
quarkus.vertx.warning-exception-time=2H
